### ISSUE TITLE
Can't compile DataFlowAnalyzer.java

### ISSUE THREAD

**Issue by czbooster** [sqlparser/gsp_demo_java#2]
Hi James,
I can't compile DataFlowAnalyzer.java, the error is like this:
`src\main\java\demos\dlineage\DataFlowAnalyzer.java:673: error: illegal start of expression
                                                Map<sourceColumn, List<Pair<sourceColumn, List<String>>>> columnMap = relationSources.stream().collect(Collectors.groupingBy(t->((Pair<sourceColumn, List<String>>)t).first));
                                                                                                                                                                               ^`
Please could you check? Thanks for adding the /i option, that's exacly what I need.
Vojtěch

**Comment by czbooster** [comment]
My fault, tried to compile with java 1.7, lambdas are supported from 1.8
